name: Create new library package

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Build app
        run: yarn && yarn build

      - name: Set NPM Token Action
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
        
          #  sh ${{ github.workspace }}/.github/workflows/publish-root-package.sh
      - name: Publish root package
        run: |
          yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}

        # yarn lerna publish from-package --yes  
      - name: Publish separate packages
        run: |
          yarn semantic-release-lerna
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}
