name: Create new library package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login in NPM
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc # put to separate script
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create new version
        run: yarn && yarn build && yarn semantic-release-root && yarn publish dist --no-git-tag-version && yarn semantic-release && lerna publish from-git
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}
          CI: true

